### PR TITLE
Advanced search

### PR DESCRIPTION
**Pull request by gavinwye**
This pull request contains the advanced search page for discussion.

I've combined all common search fields together to simplify things so searching for a 'thing' for example name will search Prisoners, Payment sources, Credits and Disbursements for the name and return results found across each of these things. 

Items on the page have been ordered roughly by usage, based on google analytics in [this sheet](https://docs.google.com/spreadsheets/d/1MxuAC61M2PVdMMQMvIW7JROso6v7JOh_AbnD3sQ9wJs/edit#gid=870010459) and then grouped into logical sections. 

Some sections have been stripped out because they were either repetitive or redundant.

### CODE REVIEW

**Comment by ushkarev** [comment]
i thought you said your intention was to use the same fields as the current live site… when we discussed it, we talked about having 4 advanced search pages (one for each of the 4 types of things you can search). the reason being that it would be really easy to introduce contradictions if it's one form and how could you present a consistent and ordered list of results when 4 types of things might be listed?

**Comment by gavinwye** [comment]
@ushkarev We did talk about that but that was before I'd looked at the analytics. As we discussed yesterday on Slack we wouldn't need an advanced search for the prisoners part as we'd be removing the things that are not used and be left with the things that are already on the prisoners' page.

I'm thinking that we will have to find a way to identify individual transaction types so there probably won't be one single table listing all of the results.

As with all of this, it calls in to question what each section of the service is there to do and what need it solves.

**Comment by ushkarev** [comment]
but you cannot remove the "my prisons" filter in the simple search so you'll never be able to get at a list of prisoners not in your prisons

**Comment by ushkarev** [comment]
I wrote that incorrectly, you’ll never get a single list with prisoners in any prison

**Comment by ushkarev** [comment]
I thought I’d drop in what we talked about today...

As a first pass at advanced search, we will make 4 separate advanced search pages such that their results lists look the same as those from the 4 simple searches. The fields we’ll use are the current lives ones, adding “currently serving” on by default and removing the 3 unused prison filters (which don’t always segment them correctly).

Some benefits of this approach being:
- simpler results lists (not having to mix credits, disbursements, prisoners and sources on one page)
- simpler advanced search forms (you can’t as easily create a contradiction that returns no results)
- the user journey is straightforward in that the user remains in the same section (the idea being they probably want to further limit the list they are seeing)

The downside still is that the user must up-front somehow decide what section to go into. That is, there’s no global search.

Does this sound good to you?

**Comment by ushkarev** [comment]
sorry, i have a few points! nothing scary :)

1) in the credits search payment method section, the "Name" field applies to both bank transfers and debit cards. but it's the same field so putting it in both sub-sections creates a potential contradiction (it doesn't make sense putting two different names in two different name boxes)
2) IP address is missing from the credits' debit card section
3) how do you want to indicate the contradictions we talked about last time?
    1) an error response after pressing search
    2) an up front error message before you press search
    3) maybe some kind of UI treatment could help –
        1) like breaking the vertical flow and putting side-by-side the sub-sections where you can only use one at a time
        2) or somehow marking fields as disabled when you fill something that contradicts another
4) maybe the prison and prisoner sections in each search should go higher up given that you've re-ordered the nav to promote these as they're used most often
5) from a personal, aesthetic point of view, i think having a field label repeat the section label looks a little repetitive. could we go for something like GDS's [header-is-also-label approach](https://design-system.service.gov.uk/patterns/question-pages/#label-as-a-page-heading)?
6) i see you've introduced "We only keep transaction data for 7 years." – this won't actually be relevant to users for another 4 years! but on that note, what about all the other similar hints that we used to have? do you think it's worth putting them here too? e.g. "you cannot see money sent by post" etc.

**Comment by gavinwye** [comment]
Thanks @ushkarev 

> 1. in the credits search payment method section, the "Name" field applies to both bank transfers and debit cards. but it's the same field so putting it in both sub-sections creates a potential contradiction (it doesn't make sense putting two different names in two different name boxes)

I've made some changes to the layout of the credits advanced search to pull the name out so that it appears above the sub-section.

> 2. IP address is missing from the credits' debit card section

Added the IP address field

> 3. how do you want to indicate the contradictions we talked about last time?

I'm planning to do this by greying out areas that can not be used but need to figure out exactly how this will work 

> 9. maybe the prison and prisoner sections in each search should go higher up given that you've re-ordered the nav to promote these as they're used most often

I'd left this at the bottom because it's prioritised in the 'simple search' so I think when people come to this page they should see things that they have not just seen. Or they may think that this is just the same as the 'simple search page'

> 10. from a personal, aesthetic point of view, i think having a field label repeat the section label looks a little repetitive. could we go for something like GDS's header-is-also-label approach?

Yea I agree with this but was trying not to break the consistent format of section heading, things you can search for. I think the heading-is-also-lable works of you just have one thing per page

> 11. i see you've introduced "We only keep transaction data for 7 years." – this won't actually be relevant to users for another 4 years! but on that note, what about all the other similar hints that we used to have? do you think it's worth putting them here too? e.g. "you cannot see money sent by post" etc.

I think it's worth looking at each of these hints and seeing if they are still needed. I just put the 7 years in as an idea. There's a lot of explaining things going on and _if we need to explain it it's not working_.

**Pull request merged**
