### PR TITLE
Added the use Firefox banner

### PR DESCRIPTION
**Pull request by gavinwye**
This PR adds the firefox banner to all pages in the service

### CODE REVIEW

**Comment by ushkarev** [comment]
quick question, are we all thinking of having this only on the dashboard page or everywhere? i lean towards everywhere personally

**Comment by JaneMOJ** [comment]
Hi. re. Firefox. 
I'm concerned some people won't know what 'browser' means. Given this banner is generated for IE8 only, could we say '...using internet explorer' which they probably know from using MS Office. 
After that initial sentence the reader is just left hanging a bit and has to go back up to the title to understand what to do. Could there be a second instructional sentence, even just a restatement 'Change .....'.  which is nice and short.

**Comment by gavinwye** [comment]
@JaneMOJ I think calling out Internet Explorer is a good idea. I'll update the content 
cc @janestead

**Comment by gavinwye** [comment]
@ushkarev everywhere

**Pull request merged**
