### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by gavinwye**
This pull request shows how notifications will work.

1. Introduction email*
2. Notification email*
3. View notifications
4. Setting page

* emails are in GOV.UK Notify not in the prototype

**1. [Notifications introduction email](https://www.notifications.service.gov.uk/services/1bbde440-eac5-43ee-86db-1fbbf28f68ce/templates/7f1f7dda-ca52-42a9-a98f-8d1ed60c6bd2)**
From this email, users can access the notifications but will only see notifications from the start of the current week. For example, if the email is sent on a Thursday, and they view the notifications page on the same Thursday they will see notifications for Monday, Tuesday, Wednesday (they don't see notifications for Thursday as these will be published on a Thursday night).

**2. [Notifications email](https://www.notifications.service.gov.uk/services/1bbde440-eac5-43ee-86db-1fbbf28f68ce/templates/ddb81312-a15b-4bf7-8b53-fb0b0b3706f9)**
This is the email that will be sent every Monday.
This email prompts users to view notifications from the previous week.

**3. [Notifications page](https://pm-intelligence-tool-pr-26.herokuapp.com/notifications/)**
Users can view notifications from the current week and page back and forward to previous weeks. Notification lists will be paginated using exsisting pagination in the money to prisoners tool when there are over 20 nitification items in the list.

**4. [Settings page](https://pm-intelligence-tool-pr-26.herokuapp.com/settings)**
Users can toggle on or off email notifications.

This pull request also contains a notification detail page but that will not be built at the moment and requires further work.

### CODE REVIEW

**Comment by janestead** [comment]
Notifications intro email
ONE - 
I think we need to keep the 2 lines as they introduce the whole thing...
So I think we should put back in...
(under Dear [User]) We've updated the prisoner money intelligence tool.
At the moment, you can search for, identify and monitor transactions in one or many prisons. But we’ve added etc etc

TWO - 
This bit at the bottom is important for ongoing improvements AND to keep the relationship between us and them going ie, it needs to be signed off form someone.
So I think under the green button, we DO need...
We hope you find the new features useful. Any feedback really helps us improve the tool further.
Kind regards, Prisoner money team

THREE - 
The line:
From now on we'll send you an email you every Monday with an overview of the last weeks transactions.
IS FINE but should read...
But, from now on, we'll email you each Monday with an overview of the past week's transactions.

**Comment by janestead** [comment]
Notifications email - all fine

**Comment by janestead** [comment]
Edit email notifications - fine.
Could the question, do you want the emails, be less heavy and smaller?
It fights with the heading at the moment? 
Otherwise, great.
As assuming this is for starting up the emails again should a user turn them off, then change their mind?

**Comment by gavinwye** [comment]
Updated the description to better reflect the current journey

**Pull request merged**
