### PR TITLE
MTP-901 - Search - Payment sources

### PR DESCRIPTION
**Pull request by gavinwye**
# Changes in this pull request

- removed links from tables with the exception of the view details link
- increased the size of the search form label
- increased the size of the search filed and simplified button layout
- moved search again button to the bottom of the results page
- duplicated this at the top thinking about this
- added pagination to the page but it's not working yet
- increased the font size of the table from 14 to 16

### CODE REVIEW

**Comment by RoseFaulkner** [comment]
In the 'about sender data' blue box I wonder if we should include some of the info can we cover in the current 'how these credits are groups'. Or is that going somewhere else? Would be worth having a quick chat about this.

In our team catch up about the prisoners page the other day we agreed we'd stay with 'payment source' rather than change to 'senders' until we have more more UR insight on this. 'Payment source' does sound odd for sure but we agreed that for now it was helpful to have that slight jar (so to speak) to remind people to pay attention.

**Comment by RoseFaulkner** [comment]
We need the prison switcher/identification of which prison the data is displayed for as the default. I know you've done this for another story, does it just need to be merged together?

**Comment by janereid73** [comment]
I'll add payment source vs payment sender to the master UR plan. It's interesting though that going through the previous UR the language used does seem to lean more towards 'sender', however given neither fully describe the page. @gavinwye @RoseFaulkner @janestead @igor I've just performed a quick search from research transcripts and the term sender is more widely used by staff, in the same research reports there was no mention of payment sources. I didn't check prototype testing papers as people could have been influenced by they saw on the screen, at the time. This quick search would suggest 'senders' is the term to use and not 'payment sources'. Here's some examples: https://docs.google.com/document/d/19CLkl-fvQ7Dh0Kifsqvp621adMtXgHAoRlckbrQcptE/edit This suggests going with senders is the right choice and we can still do more UR to understand if that needs expanded or changed in anyway.

**Comment by gavinwye** [comment]
@RoseFaulkner yes when we merge the PR for the organisation switcher #39 that will be part of the page.

**Comment by RoseFaulkner** [comment]
I wonder if 'Search again' will be missed if it's only at the bottom. Same with 'Results containing xxx from other prisons'

**Pull request merged**
